# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        my_normal:
            quality: 75
            filters:
                scale:
                    dim: [800, 520]
        my_thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        smallest:
            quality: 100
            filters:
                thumbnail:
                    size: [72, 46]