vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'title'}

    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
